name: Git Diff on Push

on:
  push:
    branches:
      - '*'

jobs:
  get-diff-and-verify:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get Git Diff
      id: git-diff
      run: |
        DIFF=$(git diff --name-only origin/${GITHUB_BASE_REF}...origin/${GITHUB_HEAD_REF})
        echo $DIFF
