name: Git Diff on Push

on:
  push:
    branches:
      - '*'

jobs:
  get-diff-and-verify:

    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: gh pr diff --name-only
