name: Git Diff on Push

on:
  push:
    branches:
      - '*'

jobs:
  get-diff-and-verify:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get Git Diff
      id: git-diff
      run: |
        DEFAULT_BRANCH=$(git remote show origin | awk '/HEAD branch/ {print $NF}')
        DIFF=$(git diff --name-only ${{ github.sha }} origin/$DEFAULT_BRANCH)
        # Set the output with newline-separated paths
        echo "::set-output name=diff::$(echo -e "$DIFF")"

    - name: Display Diff
      run: |
        echo "Changed files:"
        # Use the newline-separated paths in the subsequent steps
        echo "${{ steps.git-diff.outputs.diff }}"

    - name: Run Ruby Script
      run: |
        # Save the diff paths to a variable
        DIFF_PATHS="${{ steps.git-diff.outputs.diff }}"

        # Run a Ruby script to process the paths and execute 'omochi verify'
        ruby - <<EORUBY
          paths = ENV['DIFF_PATHS'].split("\n")

          # Iterate over paths and execute 'omochi verify' for each
          paths.each do |path|
            system("omochi verify #{path}")
          end
        EORUBY
